### ISSUE TITLE
Website leads to a parked domain

### ISSUE THREAD

**Issue by rabbithawk256** [stellophiliac/roboring#16]
Clicking on any of the webring links takes you to a parked version of your website - essentially rendering the entire thing, in a best-case, inert, and in a worst-case, a possible vector for malware

![2024-08-26-firefox-VE80n](https://github.com/user-attachments/assets/69bcbf27-47d4-4054-8de2-d3e9b50281b3)

**Comment by stellophiliac** [comment]
ah shit — the is-probably.gay domain isn't owned by me, guess the owner didn't pay for the domain or something. i'll remove the custom domain and will probably keep it that way
